### ISSUE TITLE
Snappydata-1.3.0 UnsatisfiedLinkError while starting leader

### ISSUE THREAD

**Issue by parimalaadinarayan** [TIBCOSoftware/snappydata#1565]
Hi team,

Snappyleader is not getting started when we are installing Snappydata-1.3.0, it fails to come up with below error.
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat(Ljava/lang/String;)Lorg/apache/hadoop/io/nativeio/NativeIO$POSIX$Stat;

Below are the hadoop and hbase version that we are currently using.:
Hadoop -> hadoop-2.7.5
Hbase -> hbase-1.3.1
RHEL version -> 7.7
GLIBC version -> 2.17

PFA the snappyleader.log
[snappyleader.log](https://github.com/TIBCOSoftware/snappydata/files/7595628/snappyleader.log)

**Comment by sumwale** [comment]
@parimalaadinarayan You are trying to run the SnappyData cluster itself with custom hadoop-2.7.5? The embedded cluster comes pre-bundled with hadoop 3.2.0 and changing that is not supported since a lot of internal APIs (e.g. hive metastore) depend on that minimum version.

Is there a specific reason to change to hadoop 2.7.5? A custom hadoop install is supported only for the separate Spark clusters using the smart connector mode (though 3.2.x should work for embedded cluster too).

**Comment by parimalaadinarayan** [comment]
@sumwale We are trying to upgrade snappydata only from 1.1.0 to 1.3.0 in production, In production we are using hadoop-2.7.5.
From your statement is it safe to assume that snappy 1.3.0 requires hadoop 3.2.X?
In our case, it will be helpful if snappydata works with hadoop 2.7.X ,this will avoid hadoop upgradation.

**Comment by sumwale** [comment]
@parimalaadinarayan You don't need to upgrade anything. Just remove the hadoop-2.7.5 path from cluster startup and it will use the hadoop 3.2.0 that is bundled in the product without issues. As I mentioned using a custom hadoop distribution with the embedded cluster is not supported in any case because the product uses it for hive-metastore and some other stuff internally and switching to external hadoop distribution may break things in subtle ways. For accessing external hadoop data sources from embedded cluster, just use the hadoop URLs as usual which will work with bundled 3.2.0 without issues since 3.2.0 client is backward compatible. If that causes trouble then that is a real issue that will need to be fixed.

You can use custom hadoop in smart connector mode with the Apache Spark cluster. Download the "without-hadoop" packages from https://archive.apache.org/dist/spark/spark-2.1.3 or use SnappyData distribution itself for the spark cluster after removing hadoop-* from jars directory (of course, as mentioned don't do that for the SnappyData cluster).

**Comment by parimalaadinarayan** [comment]
Thanks @sumwale your suggestion worked.
