### ISSUE TITLE
SnappyData- 1.3.0 Persistence 'none' is throwing exception.

### ISSUE THREAD

**Issue by parimalaadinarayan** [TIBCOSoftware/snappydata#1567]
When we try to create snappydata tables with persistence none in snappydata - 1.3.0  is throwing exception.
We would need to store some tables as in memory whereas it is not required for all the tables.
Please let us know how to create a in-memory columnar table.
Below is the script we are using to create tables
`CREATE TABLE test(IMSI STRING,MSISDN STRING) USING column OPTIONS(REDUNDANCY '1', BUCKETS '128', PERSISTENCE 'NONE');`
Below is the error:
`ERROR 42000: (SQLState=42000 Severity=20000) (Server=DEV-BDSP-Worker-07/10.49.3.107[1528] Thread=ThriftProcessor-222) Syntax error or analysis exception: Column tables do not support persistence = none;
 `
 This was working fine with snappydata - 1.1.0

**Comment by sumwale** [comment]
@parimalaadinarayan This is by design. Column tables are supposed to hold medium/large amount of data that may not be held in memory completely. Otherwise data can disappear in the middle of an operation when there is memory pressure and the table data gets evicted.

Only row tables allow for this, and it is supposed to be used for small amounts of transient data like temporary tables. Even for the row tables you should combine it with "EVICTION_BY 'none'" to ensure that data cannot be evicted in the middle of operations. Otherwise it can lead easily to data inconsistency problems at the application level.
